# Generated by Django 3.1.3 on 2020-12-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('label_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'class_label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('label_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'difficulty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('label_name', models.TextField(unique=True)),
                ('label_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testgroup',
            fields=[
                ('label_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'testgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('pixel_width', models.IntegerField()),
                ('pixel_height', models.IntegerField()),
                ('fps', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
