# Generated by Django 3.1.3 on 2021-01-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.TextField(primary_key=True, serialize=False)),
                ('video_link_id', models.TextField(unique=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.class')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_pause', models.IntegerField()),
                ('replay', models.IntegerField()),
                ('fullscreen', models.IntegerField()),
                ('playback', models.IntegerField()),
                ('duration_in_sec', models.IntegerField()),
                ('text', models.TextField(max_length=300)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.class')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.difficulty')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Start.user')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classification.video')),
            ],
            options={
                'db_table': 'classification',
                'unique_together': {('session_id', 'video_id')},
            },
        ),
    ]
