# Generated by Django 3.1.3 on 2021-01-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Start', '0001_initial'),
        ('Classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.class'),
        ),
        migrations.AddField(
            model_name='classification',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.class'),
        ),
        migrations.AddField(
            model_name='classification',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Start.difficulty'),
        ),
        migrations.AddField(
            model_name='classification',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Start.user'),
        ),
        migrations.AddField(
            model_name='classification',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classification.video'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('session_id', 'video_id')},
        ),
    ]
